### ISSUE TITLE
Any update on code release?

### ISSUE THREAD

**Issue by dgrahn** [DBay-ani/Fanoos#1]
Any update on code release?

**Comment by DBay-ani** [comment]
Your question comes with good timing and bad timing. We're in the process of clearing a few final approval hurdles. Its a headache, but it should be up in the next week or two weeks, preferably the former. If its not with in this time frame, please shoot me a message laced with profanity.

**Comment by DBay-ani** [comment]
Code to be released before midnight, Monday, March 22nd, 2021, but likely not before midnight Sunday owing to (1) related public releases, which we do not have the ability to move forward, mechanically set to occur for the evening of the 22nd, (2) the start of the [holiday](https://en.wikipedia.org/wiki/Nowruz) prior. In the  meantime, we intend to post the license file, Dockerfile with related scripts, and instructions for install on AWS not requiring Docker.

**Comment by DBay-ani** [comment]
Addressed
